"""mkdocs hook: generate the sample application AT DOCS-BUILD TIME.

WHY THIS IS A HOOK AND NOT FOUR COMMITTED FILES

Through 1.2.0 the repo carried examples/sample_output/*.{md,docx,pdf,xlsx},
generated once and committed. They were linked from README.md as "Generated
outputs ... for a realistic sample CDE application", and by the time 1.2.0 was
cut they were nine months stale — still carrying the complete 1.1.5 fabrication
set that the release notes said had been removed. Extracted from the committed
.docx at f71ebbc:

    2.3× | denial rates | HMDA 5-year data | 2018-2022 | racial disparities
    | minority applicants | CDFI Fund Competitive Minimum
    | zero compliance violations | within 18 months of award

Nine of the eighteen strings in the regression denylist, in a ready-to-open
Word document, offered to CDEs as the model to copy. The fabrication gate could
not see them: it renders fresh artifacts into a temp directory and reads what
it just produced, so a committed artifact is outside its world by construction.

The fix is not to scan committed artifacts. It is to have none. Generating at
build time means the published sample is, always and by construction, what the
current code produces — and if generation fails, the docs say so rather than
quietly serving something older.

The generated files land in ``<site>/sample-output/`` and are never written
back into the source tree. ``examples/sample_output/`` is gitignored so a
local experiment cannot recommit them.
"""
from __future__ import annotations

import logging
import os
import shutil
import tempfile
import traceback

log = logging.getLogger("mkdocs.hooks.sample_output")

_SUBDIR = "sample-output"

_PAGE_HEADER = """# Sample Output

These files were generated by the version of nmtc-application-builder in this
repository, at the moment these docs were built. They are not committed to the
repository and cannot go stale.

!!! warning "Fictional data"
    The CDE in these documents — Riverbend Community Capital CDE, LLC — does
    not exist, and neither do its projects, addresses or figures. The package
    refuses to score or generate against this identity outside demo mode; see
    `nmtcapp/core/sample_identity.py`.

Note how much of the document is `[CDE TO COMPLETE: ...]`. That is the point:
this tool assembles and computes what it can derive from your own inputs, and
marks everything else as yours to write.

"""


def _build_sample(out_dir: str) -> list:
    """Render the sample application into out_dir. Returns written filenames."""
    from nmtcapp.core.application import Application
    from nmtcapp.core.cde import CDEProfile
    from nmtcapp.core.pipeline import Pipeline

    app = Application(cde=CDEProfile.sample(), requested_allocation=65_000_000)
    app.add_pipeline(Pipeline.sample(n=20))
    paths = app.generate(out_dir, formats=["markdown", "word", "excel", "pdf"])
    return sorted(os.path.basename(p) for p in paths.values())


def on_post_build(config, **kwargs):  # noqa: D103 - mkdocs hook signature
    site_dir = config["site_dir"]
    out_dir = os.path.join(site_dir, _SUBDIR)
    os.makedirs(out_dir, exist_ok=True)

    tmp = tempfile.mkdtemp(prefix="nmtcapp-sample-")
    try:
        written = _build_sample(tmp)
        for name in written:
            shutil.copy2(os.path.join(tmp, name), os.path.join(out_dir, name))
        log.info("sample output generated: %s", ", ".join(written))
        body = _PAGE_HEADER + "\n".join(f"- [`{n}`]({n})" for n in written) + "\n"
    except Exception:
        # Say so in the published docs. A silent failure here is how a stale
        # artifact survives; an empty page with an explanation is not.
        log.error("sample output generation FAILED:\n%s", traceback.format_exc())
        body = (
            _PAGE_HEADER
            + "!!! failure \"Generation failed during this docs build\"\n"
            + "    No sample output is published for this build. Run\n"
            + "    `python -m mkdocs build` locally to see the traceback.\n"
            + "    Nothing stale is served in its place.\n"
        )

    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(_html(body))


def _html(markdown_body: str) -> str:
    """Minimal standalone page — the hook runs after the theme has rendered."""
    import html
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<title>Sample Output — NMTC Application Builder</title>"
        "<style>body{font:16px/1.6 system-ui,sans-serif;max-width:44rem;"
        "margin:3rem auto;padding:0 1rem}code{background:#eee;padding:.1em .3em}"
        "</style></head><body><pre style='white-space:pre-wrap'>"
        + html.escape(markdown_body)
        + "</pre></body></html>"
    )
