"""mkdocs hook: generate the sample application AT DOCS-BUILD TIME.

WHY THIS IS A HOOK AND NOT FOUR COMMITTED FILES

Through 1.2.0 the repo carried examples/sample_output/*.{md,docx,pdf,xlsx},
generated once and committed. They were linked from README.md as "Generated
outputs ... for a realistic sample CDE application", and by the time 1.2.0 was
cut they were nine months stale — still carrying the complete 1.1.5 fabrication
set that the release notes said had been removed. Extracted from the committed
.docx at f71ebbc:

    2.3× | denial rates | HMDA 5-year data | 2018-2022 | racial disparities
    | minority applicants | CDFI Fund Competitive Minimum
    | zero compliance violations | within 18 months of award

Nine of the eighteen strings in the regression denylist, in a ready-to-open
Word document, offered to CDEs as the model to copy. The fabrication gate could
not see them: it renders fresh artifacts into a temp directory and reads what
it just produced, so a committed artifact is outside its world by construction.

The fix is not to scan committed artifacts. It is to have none. Generating at
build time means the published sample is, always and by construction, what the
current code produces — and if generation fails, the docs say so rather than
quietly serving something older.

The generated files land in ``<site>/sample-output/`` and are never written
back into the source tree. ``examples/sample_output/`` is gitignored so a
local experiment cannot recommit them.
"""
from __future__ import annotations

import logging
import os
import shutil
import tempfile
import traceback

log = logging.getLogger("mkdocs.hooks.sample_output")

_SUBDIR = "sample-output"

_PAGE_HEADER = """# Sample Output

These files were generated by the version of nmtc-application-builder in this
repository, at the moment these docs were built. They are not committed to the
repository and cannot go stale.

!!! warning "Fictional data — and the package did not stop this page making it"
    The CDE in these documents — Riverbend Community Capital CDE, LLC — does
    not exist, and neither do its projects, addresses or figures.

    These files were produced by calling `CDEProfile.sample()` and then
    `Application.generate()`, which is the path this page's own build takes.
    **The package does not refuse that path.** The refusal in
    `nmtcapp/core/sample_identity.py` sits on the two places where an identity
    *you* supply is read: `CDEProfile.from_yaml()`, which raises unless it is
    passed `allow_sample=True` — and so `nmtcapp analyze --cde` refuses this
    identity too — and the Streamlit CDE Profile upload. Neither
    `CDEProfile.sample()` nor `Application.generate()` checks anything, so a
    script that starts from the sample profile produces documents like these
    without objection. Do not file them.

Note how much of the document is `[CDE TO COMPLETE: ...]`. That is the point:
this tool assembles and computes what it can derive from your own inputs, and
marks everything else as yours to write.

"""


_FORMATS = ("markdown", "word", "excel", "pdf")


def _build_sample(out_dir: str) -> list:
    """Render the sample application into out_dir. Returns written filenames.

    RAISES IF ANY CONFIGURED FORMAT IS MISSING, and that is the 1.2.1 fix.

    Application.generate() catches ImportError per format and logs a warning,
    so on a machine without the output extras it returns the subset that
    worked. This hook then reported success::

        python-docx not installed — skipping Word output
        reportlab not installed — skipping PDF output
        INFO - sample output generated: CDE-2018-0117_application.md,
                                        CDE-2018-0117_application.xlsx
        INFO - Documentation built in 8.36 seconds     <- --strict, and it passed

    Two of four formats, a green --strict build, and
    docs/workflow/output-formats.md telling the reader "A complete sample in
    all four formats is generated fresh on every docs build". The eleventh
    instance in this package of a gate that cannot fail, and it was found by
    hand on the deploy that fixed a fabricated citation.

    Comparing what was asked for against what came back is the whole fix. The
    page's claim is the thing a reader relies on, so the build stops rather
    than the page quietly describing less.
    """
    from nmtcapp.core.application import Application
    from nmtcapp.core.cde import CDEProfile
    from nmtcapp.core.pipeline import Pipeline

    app = Application(cde=CDEProfile.sample(), requested_allocation=65_000_000)
    app.add_pipeline(Pipeline.sample(n=20))
    paths = app.generate(out_dir, formats=list(_FORMATS))

    missing = sorted(set(_FORMATS) - set(paths))
    if missing:
        raise RuntimeError(
            f"sample output is missing {len(missing)} of {len(_FORMATS)} "
            f"formats: {', '.join(missing)}. Application.generate() skips a "
            "format whose renderer will not import, so this is almost always "
            "the output extras not being installed. Install the docs "
            "toolchain with `pip install -e \".[docs]\"` and rebuild. The "
            "published page claims all four formats; it must not be built "
            "from fewer."
        )
    return sorted(os.path.basename(p) for p in paths.values())


def on_post_build(config, **kwargs):  # noqa: D103 - mkdocs hook signature
    site_dir = config["site_dir"]
    out_dir = os.path.join(site_dir, _SUBDIR)
    os.makedirs(out_dir, exist_ok=True)

    tmp = tempfile.mkdtemp(prefix="nmtcapp-sample-")
    try:
        written = _build_sample(tmp)
        for name in written:
            shutil.copy2(os.path.join(tmp, name), os.path.join(out_dir, name))
        log.info("sample output generated: %s", ", ".join(written))
        body = _PAGE_HEADER + "\n".join(f"- [`{n}`]({n})" for n in written) + "\n"
    except Exception:
        # Say so in the published docs AND fail the build. A silent failure
        # here is how a stale artifact survives; an explanatory page is better
        # than a stale one, but neither is good enough on its own, because a
        # green --strict build is what a maintainer actually reads.
        log.error("sample output generation FAILED:\n%s", traceback.format_exc())
        body = (
            _PAGE_HEADER
            + "!!! failure \"Generation failed during this docs build\"\n"
            + "    No sample output is published for this build. Run\n"
            + "    `python -m mkdocs build` locally to see the traceback.\n"
            + "    Nothing stale is served in its place.\n"
        )
        with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as fh:
            fh.write(_html(body))
        raise

    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(_html(body))


def _html(markdown_body: str) -> str:
    """Minimal standalone page — the hook runs after the theme has rendered."""
    import html
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<title>Sample Output — NMTC Application Builder</title>"
        "<style>body{font:16px/1.6 system-ui,sans-serif;max-width:44rem;"
        "margin:3rem auto;padding:0 1rem}code{background:#eee;padding:.1em .3em}"
        "</style></head><body><pre style='white-space:pre-wrap'>"
        + html.escape(markdown_body)
        + "</pre></body></html>"
    )
