"""The workbook says which build made it, and no file names its library as author.

TWO DEFECTS (1.7.1 R6, R7), measured on the published 1.7.0 artifacts:

R6  ``1.7.0`` appears in no cell of any of the nine sheets. Markdown, Word
    and PDF each say "generated by nmtc-application-builder v1.7.0"; the
    workbook says "Generated <date>" and nothing else. That stamp is the
    diagnostic that caught BOTH the 1.6.5 and the 1.7.0 P0 — each stale
    sample was identified in one read because its cover said the old
    version — and the workbook, the format most likely to be forwarded to
    an investor, could not be diagnosed that way.

R7  ``.docx`` author ``python-docx``, comments "generated by python-docx",
    created AND modified ``2013-12-23T23:15Z`` (python-docx's template).
    ``.xlsx`` creator ``openpyxl``, title None. Neither renderer ever set a
    property, so a CDE filed its library's defaults with a federal agency.
    credit-memo 0.2.2 fixed exactly this five days before 1.7.0 shipped.

WHAT IS SET, AND FROM WHERE. Author/creator is the CDE's name — a required
profile field. Title is the CDE's name and the round phrase the running
headers already use. Comments/description name the package and version.
Word's created/modified are the generation time, replacing the template's
2013 date. NOTHING IS INVENTED: no subject, keywords, category or manager
— the profile carries none, and an empty property is honest where a
guessed one is not.

Two-sided throughout: the library default is absent AND the CDE's value is
present, on every property this module names.
"""
from __future__ import annotations

import datetime

import pytest


@pytest.fixture(scope="module")
def rendered(tmp_path_factory) -> tuple:
    from nmtcapp.core.application import Application
    from tests.test_rendered_output_baseline import (
        APPLICATION_ROUND, REQUESTED_ALLOCATION, _cde, _pipeline,
    )

    app = Application(cde=_cde(), requested_allocation=REQUESTED_ALLOCATION,
                      application_round=APPLICATION_ROUND)
    app.add_pipeline(_pipeline())
    out = str(tmp_path_factory.mktemp("properties"))
    paths = app.generate(out, formats=["word", "excel"])
    assert {"word", "excel"} <= set(paths)
    return app, paths


def _docx_props(path: str) -> dict:
    import docx
    cp = docx.Document(path).core_properties
    return {k: getattr(cp, k) for k in (
        "author", "title", "comments", "subject", "keywords", "category",
        "last_modified_by", "created", "modified", "revision",
    )}


def _xlsx_props(path: str) -> dict:
    import openpyxl
    p = openpyxl.load_workbook(path, read_only=True).properties
    return {k: getattr(p, k) for k in (
        "creator", "title", "description", "subject", "keywords", "category",
        "lastModifiedBy", "created", "modified",
    )}


# --- R6 ---------------------------------------------------------------------

def test_the_summary_dashboard_stamps_the_package_version(rendered):
    import openpyxl
    from nmtcapp import __version__

    _app, paths = rendered
    wb = openpyxl.load_workbook(paths["excel"], read_only=True)
    ws = wb["Summary Dashboard"]
    stamp = f"nmtc-application-builder v{__version__}"
    cells = [c.coordinate for row in ws.iter_rows() for c in row
             if isinstance(c.value, str) and stamp in c.value]
    assert len(cells) == 1, (
        f"the Summary Dashboard should carry {stamp!r} in exactly one cell; "
        f"found it in {cells}. Without it a stale workbook cannot be told from "
        "a fresh one, which is how the 1.6.5 and 1.7.0 P0s were caught on the "
        "other three formats."
    )
    text = ws[cells[0]].value
    assert "Generated " in text, (
        "the stamp is not beside the generated-date line: " + text
    )


def test_the_version_stamp_reads_the_package_not_a_literal(rendered, monkeypatch):
    """The stamp must move with nmtcapp.__version__, never be typed."""
    import openpyxl
    import nmtcapp
    from nmtcapp.renderers.excel_builder import ExcelApplicationBuilder

    app, _paths = rendered
    monkeypatch.setattr(nmtcapp, "__version__", "99.0.0.mutant")
    wb = ExcelApplicationBuilder(app, app.analyze()).build()
    ws = wb["Summary Dashboard"]
    hits = [c.value for row in ws.iter_rows() for c in row
            if isinstance(c.value, str) and "99.0.0.mutant" in c.value]
    assert len(hits) == 1, "the workbook did not pick up a changed __version__"


# --- R7 ---------------------------------------------------------------------

def test_word_properties_name_the_cde_and_the_package(rendered):
    from nmtcapp import __version__
    from nmtcapp.renderers._document_properties import document_title

    app, paths = rendered
    props = _docx_props(paths["word"])
    assert props["author"] == app.cde.name
    assert props["title"] == document_title(app)
    assert f"nmtc-application-builder v{__version__}" in props["comments"]
    assert props["created"].year >= 2026, props["created"]
    assert props["modified"] == props["created"]
    # Not invented: the profile carries none of these.
    assert props["subject"] == ""
    assert props["keywords"] == ""
    assert props["category"] == ""


def test_word_properties_carry_no_library_default(rendered):
    _app, paths = rendered
    props = _docx_props(paths["word"])
    leaked = {k: v for k, v in props.items()
              if isinstance(v, str) and "python-docx" in v.lower()}
    assert not leaked, f"python-docx's defaults still in the file: {leaked}"
    assert props["created"] != datetime.datetime(2013, 12, 23, 23, 15, tzinfo=datetime.timezone.utc), (
        "created is python-docx's template date, not the generation time"
    )


def test_excel_properties_name_the_cde_and_the_package(rendered):
    from nmtcapp import __version__
    from nmtcapp.renderers._document_properties import document_title

    app, paths = rendered
    props = _xlsx_props(paths["excel"])
    assert props["creator"] == app.cde.name
    assert props["title"] == document_title(app)
    assert f"nmtc-application-builder v{__version__}" in props["description"]
    assert props["subject"] is None
    assert props["keywords"] is None
    assert props["category"] is None
    assert props["created"] is not None and props["created"].year >= 2026


def test_excel_properties_carry_no_library_default(rendered):
    _app, paths = rendered
    props = _xlsx_props(paths["excel"])
    leaked = {k: v for k, v in props.items()
              if isinstance(v, str) and "openpyxl" in v.lower()}
    assert not leaked, f"openpyxl's defaults still in the file: {leaked}"


def test_the_title_is_built_from_what_the_profile_supplies():
    from nmtcapp.core.application import Application
    from nmtcapp.core.cde import CDEProfile
    from nmtcapp.renderers._document_properties import document_title

    cde = CDEProfile.sample()
    with_round = Application(cde=cde, requested_allocation=1.0, application_round="CY 2026")
    without = Application(cde=cde, requested_allocation=1.0)
    assert document_title(with_round) == f"{cde.name} — NMTC CY 2026 Allocation Application"
    assert document_title(without) == f"{cde.name} — NMTC Allocation Application"
    assert "None" not in document_title(without)
