"""THE attribution gate: a rendered claim that credits an authority, or asserts a rank, must carry a citation.

WHY THIS AND NOT THE INVARIANCE GATE

tests/test_invariant_output.py fails any prose line byte-identical across four
disjoint scenarios. That catches a claim the tool makes about EVERY CDE. It
cannot, by construction, catch a claim that VARIES with the input and is still
unsupportable — because varying is exactly what makes it look derived.

vs_historical_benchmarks was the proof. It rendered

    • 7.0 jobs per $1MM of QEI deployed (average vs. CDFI Fund historical average)

and the label moved between "average" and "top_quartile" depending on the
pipeline, so the invariance gate never saw it. It came from a single >=
against one uncited number. Three instances of that shape have now been found
in three separate passes, each by someone looking for something else.

This gate keys on the property those three shared and the invariance gate is
blind to: they credited an outside authority, or asserted a rank, without a
citation.

THE RULE

Over the same four disjoint scenarios and four formats the invariance gate
renders, every prose clause containing an attribution or rank marker must be on
tests/attribution_allowlist.txt, carrying either

  CITED    a document, section and where possible a URL
  HOUSE    an explicit house-heuristic marker — and the RENDERED TEXT must say
           so on its face, not merely the allowlist entry
  PLACEHO  the clause sits inside bracketed [CDE TO COMPLETE] / [NARRATIVE
           PLACEHOLDER] guidance, which is marked on its face as instruction to
           the CDE rather than an assertion in the CDE's voice
  LABEL    a bare column or row label containing a trigger word ("Median Family
           Income"), which names a field rather than claiming anything

A citation recorded here is recorded, not verified. Auditing each source
document is the next release's work; what this gate enforces is that a claim
cannot reach a CDE's filing without SOMEBODY having had to write down where it
came from.

FAILS CLOSED. Fewer than four scenarios, an empty scan, an empty match set, or
a missing format all error rather than pass.
"""
from __future__ import annotations

import os
import re

import pytest

# Shares the rendering fixtures with the invariance gate rather than
# duplicating four scenarios that would then drift apart.
from tests.test_invariant_output import (  # noqa: E402
    FORMATS, MIN_SCENARIOS, SCENARIOS, _extract, _is_prose,
)
from nmtcapp.core.application import Application

ALLOWLIST_PATH = os.path.join(os.path.dirname(__file__), "attribution_allowlist.txt")


# ---------------------------------------------------------------------------
# Triggers
#
# The starting set came from the FIX-2 brief. Everything after the blank line
# was added from the rendered corpus itself and from the comparative-label
# enumeration (11 functions under nmtcapp/ return a closed set of string
# literals; 7 of those sets are comparative). The corpus is the authority: a
# trigger guessed in advance is both too broad and incomplete.
# ---------------------------------------------------------------------------
TRIGGERS = [
    # from the brief
    "cdfi fund", "historical", "historically", "average", "median", "quartile",
    "percentile", "benchmark", "typical", "industry", "peer", "versus", "vs.",
    "compared", "ranks", "rank", "tier",
    # added from the corpus + the shape enumeration
    "above-average", "below-average", "above average", "below average",
    "outperform", "underperform", "top quartile", "national", "winners",
    "winning", "competitive", "strongest", "leading", "best-in-class",
]

# ---------------------------------------------------------------------------
# Narrowings. Each is a decision to NOT count something as a match, recorded
# here rather than by deleting a trigger — deleting a trigger makes the gate
# silently narrower forever; a narrowing is reviewable.
# ---------------------------------------------------------------------------

# N1. A clause that DISCLAIMS an attribution is the opposite of making one.
#     "$0.83 (market assumption, not a CDFI Fund parameter)" names the CDFI
#     Fund in order to say the number is not theirs. Counting it would push the
#     gate toward rewarding silence over disclosure.
_DISCLAIMERS = (
    "not a cdfi fund parameter",
    "publishes no such",
    "unsourced house heuristic",
    "does not predict an award",
    "not calibrated against award data",
    "not generated by this tool",
    "does not compute, retrieve or verify",
    "this tool has no",
    "this tool holds no",
    "holds no investor data",
    "cannot attest",
    "supplies no figure",
    "this tool's own assessment against its own",
    "this tool's impact-score threshold",
    "it is not a cdfi fund threshold",
    "this tool's own internal scoring band",
    # Added in 1.2.0 with the F28 relabel. These clauses name the CDFI Fund in
    # order to say the figure is NOT theirs — the paradigm case for N1. If they
    # counted as matches, the gate would penalise the disclosure that fixed the
    # defect and reward going quiet instead.
    "publishes no jobs-per-qei benchmark",
    "not a cdfi fund figure",
    "no band here is a percentile",
    "these are not a federal figure",
    "this tool's own bands",
    "this tool's own bands (",
)

# N2. Placeholder text is the ABSENCE of a claim. A [CDE TO COMPLETE] block
#     that tells the CDE to cite its sources to the CDFI Fund is the behaviour
#     this gate wants, not a violation of it.
_PLACEHOLDER_MARKS = ("[cde to complete", "[narrative placeholder")

# N3. A per-row DATA SOURCE citation in a table is a citation — that is the
#     column's entire job. The citation string itself is allowlisted once; the
#     rows carrying it are then satisfied. Without this, eighteen near-identical
#     project rows would each need their own entry and the list would stop
#     being reviewable, which is the failure mode the brief warns about.
_ROW_CITATIONS = ("cdfi fund nmtc eligibility table",)

# N4. A CDE's own profile field rendered back to it is not an attribution.
#     "was certified as a Community Development Entity by the CDFI Fund on
#     2011-01-05" restates cde.certification_date, which the CDE supplied.
#     Matches the wrapped continuation too ("cdfi fund on 2011-01-05"), which
#     the PDF and Word extractors produce mid-sentence.
_SELF_REPORTED = ("was certified as a community development entity by the cdfi fund",
                  "cdfi fund on ")

# N5. The confidentiality banner names the Fund as the AUDIENCE, not as a
#     source for any figure.
_AUDIENCE = ("prepared for cdfi fund review only",)


def _normalise(clause: str) -> str:
    """Collapse a clause to its attributive shape: lowercase, digits -> N.

    Keys the allowlist on the CLAIM rather than on the numbers around it, so
    four scenarios producing four dollar figures share one reviewable entry.
    """
    s = clause.strip().lower()
    s = re.sub(r"\d[\d,._]*", "N", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip(" |-—*")


def _clauses(line: str):
    """Split a rendered line into clauses: table cells, then sentences."""
    for cell in line.split(" | "):
        for part in re.split(r"(?<=[.;])\s+", cell):
            if part.strip():
                yield part.strip()


def _exempt(clause_lower: str, line_lower: str) -> str | None:
    """Return the narrowing that exempts this clause, or None."""
    if any(m in line_lower for m in _PLACEHOLDER_MARKS):
        return "N2 placeholder"
    if any(d in clause_lower for d in _DISCLAIMERS):
        return "N1 disclaimer"
    if any(c in clause_lower for c in _ROW_CITATIONS):
        return "N3 per-row data-source citation"
    if any(s in clause_lower for s in _SELF_REPORTED):
        return "N4 CDE's own profile field"
    if any(a in clause_lower for a in _AUDIENCE):
        return "N5 names the Fund as audience, not source"
    return None


def _load_allowlist() -> dict:
    entries = {}
    with open(ALLOWLIST_PATH, encoding="utf-8") as fh:
        for raw in fh:
            if not raw.strip() or raw.startswith("#"):
                continue
            kind, citation, claim = raw.rstrip("\n").split(" | ", 2)
            entries[claim] = (kind, citation)
    return entries


# ---------------------------------------------------------------------------
# N6. A CLAUSE THAT IS A PIECE OF AN ALREADY-RULED CLAUSE IS RULED.
#
#     Added in 1.3.0 FIX-2 B1. Fixing the PDF's key/value tables so their cells
#     WRAP splits sentences across visual lines, and this gate's unit is a
#     line. Six clauses appeared that way, every one of them a contiguous piece
#     of a clause the corpus already carries whole — four of allowlisted
#     entries, two of N1-disclaimed ones, and the two disclaimed ones are the
#     sharper case:
#
#         "$0.83 (market assumption, not a CDFI Fund parameter)"
#
#     is exempt because "not a cdfi fund parameter" is in _DISCLAIMERS. Wrapped
#     after "Fund", the disclaimer is on the next line and N1 misses a
#     disclosure that is fully present in the document. Ruling the fragment as
#     an unattributed claim would penalise the sentence for being long enough
#     to wrap.
#
#     THE PARENT MUST BE IN THIS SAME CORPUS AND MUST ITSELF BE RULED OR
#     EXEMPT. A fragment of nothing is still reported; see
#     test_the_wrap_narrowing_cannot_absorb_a_new_claim. The gate prints the
#     absorbed count so it cannot grow unnoticed.
# ---------------------------------------------------------------------------

#: See tests/test_invariant_output.MIN_FRAGMENT_CHARS — same reasoning, and the
#: clause corpus is finer-grained than the line corpus, so the floor matters
#: more here.
MIN_FRAGMENT_CHARS = 20


def wrapped_fragments(clauses, ruled) -> dict:
    """Return ``{clause: parent}`` for each clause that is a piece of a ruled one.

    Example::

        wrapped_fragments({"not a cdfi fund"}, {"not a cdfi fund parameter)"})
    """
    absorbed = {}
    # Deterministic, for the reason tests/test_invariant_output records at the
    # same function: `ruled` is a set, and taking whichever parent hash order
    # reached first made the PARENT count vary run to run on an unchanged tree
    # while the gate printed it as a fact (1.3.1 G5).
    candidates = sorted(ruled, key=lambda p: (-len(p), p))
    for clause in sorted(clauses):
        if len(clause) < MIN_FRAGMENT_CHARS:
            continue
        for parent in candidates:
            if len(parent) > len(clause) and clause in parent:
                absorbed[clause] = parent
                break
    return absorbed


def _assert_every_absorption_is_a_wrap(absorbed: dict, seen_on: dict) -> None:
    """N6's narrowing must swallow wraps and nothing else — asserted, not printed.

    THE COUNT USED TO BE PRINTED (1.3.1 G5). ``print("N6 absorbed 6 ...")`` in
    a passing test is read by nobody, and the parent half of it was not even
    stable: `wrapped_fragments` took its parent from an unordered set, so the
    same tree printed 8, 9, 10 and 13 across PYTHONHASHSEED values.

    What is asserted instead is the property the narrowing actually claims,
    stated the same way ``tests/test_invariant_output`` states it: A WRAP IS
    ONE CLAUSE SEEN THROUGH TWO GEOMETRIES. Markdown, Word and Excel carry the
    long cells unbroken; the PDF lays them into a 194 pt column and splits
    them across visual lines, and this gate's unit is a line. So a genuine
    fragment appears on a surface its parent does not.

    A clause that renders BESIDE its supposed parent, on the same surface, was
    not wrapped by anything. Absorbing it would let a new uncited attribution
    inherit a ruling by being a substring of one — which is precisely the
    class this gate exists to report.
    """
    assert absorbed, (
        "N6 absorbed nothing. The PDF wraps the long key/value cells this "
        "narrowing was added for, so some fragments must exist; if none do, "
        "extraction changed shape and the narrowing is dead code."
    )
    not_wraps = []
    for clause, parent in sorted(absorbed.items()):
        shared = seen_on.get(clause, set()) & seen_on.get(parent, set())
        if not seen_on.get(clause) or not seen_on.get(parent):
            not_wraps.append(f"not indexed on any surface: {clause[:70]!r}")
        elif shared:
            not_wraps.append(
                f"on {sorted(shared)} this clause renders BESIDE the ruled "
                f"clause it is treated as a wrap of:\n      clause: "
                f"{clause[:90]!r}\n      parent: {parent[:90]!r}"
            )
    assert not not_wraps, (
        f"{len(not_wraps)} of {len(absorbed)} absorbed clause(s) are not "
        "wraps. N6 exists so one sentence does not need nine rulings because "
        "the PDF broke it across nine lines; it is not a licence for an "
        "uncited claim to inherit a ruling by being a substring of one.\n\n  "
        + "\n\n  ".join(not_wraps[:10])
    )


@pytest.fixture(scope="module")
def attributed_clauses(tmp_path_factory) -> dict:
    """{normalised clause: (example line, triggers)} across all scenarios/formats.

    Clauses that N6 absorbs — pieces of a clause the same corpus carries whole
    and already ruled or exempt — are removed here rather than in the gate, so
    the dead-entry check sees the same set the gate does.
    """
    found = {}
    exempted = set()
    scanned = 0
    seen_on: dict = {}          # normalised clause -> {format, ...}
    for sid, (cde, pipeline, requested) in SCENARIOS.items():
        out = tmp_path_factory.mktemp(f"attr{sid}")
        app = Application(cde=cde, requested_allocation=requested)
        app.add_pipeline(pipeline)
        paths = app.generate(str(out), formats=list(FORMATS))
        assert set(paths) == set(FORMATS), (
            f"scenario {sid} rendered {sorted(paths)}; a format that does not "
            "render is a format this gate is not scanning"
        )
        for fmt, path in paths.items():
            text = _extract(fmt, path)
            assert text.strip(), f"scenario {sid}: {fmt} extracted empty"
            for line in text.splitlines():
                line = line.strip()
                if not _is_prose(line):
                    continue
                scanned += 1
                low = line.lower()
                for clause in _clauses(line):
                    cl = clause.lower()
                    seen_on.setdefault(_normalise(clause), set()).add(fmt)
                    hits = [t for t in TRIGGERS if t in cl]
                    if not hits:
                        continue
                    if _exempt(cl, low):
                        exempted.add(_normalise(clause))
                        continue
                    found.setdefault(_normalise(clause), (line, sorted(set(hits))))
    # N6: a piece of a clause this corpus carries whole, and rules or exempts
    # there, is the same clause seen through a line break.
    ruled = set(_load_allowlist()) | exempted
    absorbed = wrapped_fragments(set(found) - ruled, ruled)
    _assert_every_absorption_is_a_wrap(absorbed, seen_on)
    for clause in absorbed:
        found.pop(clause, None)
    assert scanned > 200, (
        f"only {scanned} prose lines scanned across {len(SCENARIOS)} scenarios "
        "x 4 formats — extraction is broken, and this gate would pass vacuously"
    )
    return found


def test_scenario_count_is_sufficient():
    assert len(SCENARIOS) >= MIN_SCENARIOS, (
        f"{len(SCENARIOS)} scenarios; need at least {MIN_SCENARIOS}"
    )


def test_allowlist_entries_carry_a_citation():
    allow = _load_allowlist()
    assert allow, "the attribution allowlist is empty — every match would fail"
    for claim, (kind, citation) in allow.items():
        assert kind in {"CITED", "HOUSE", "PLACEHO", "LABEL"}, (
            f"unknown kind {kind!r} for {claim[:60]!r}"
        )
        assert len(citation.strip()) >= 12, (
            f"allowlist entry has no real citation: {claim[:60]!r}"
        )
        if kind == "CITED":
            assert any(ch.isdigit() for ch in citation), (
                f"a CITED entry must name a document with a year, section or "
                f"number: {claim[:60]!r} -> {citation!r}"
            )


def test_scan_is_not_empty(attributed_clauses):
    """Fail closed: no matches at all means the triggers or the scan broke."""
    assert attributed_clauses, (
        "no attributed clause was found in any rendered artifact. The document "
        "cites the CDFI Fund eligibility table and the CY 2024-2025 threshold, "
        "so zero matches means the scan is broken, not that the output is clean."
    )


def test_every_attributed_claim_is_cited(attributed_clauses):
    """The gate."""
    allow = _load_allowlist()
    unlisted = sorted(set(attributed_clauses) - set(allow))
    if unlisted:
        detail = []
        for claim in unlisted:
            line, triggers = attributed_clauses[claim]
            detail.append(
                f"  trigger {triggers}\n"
                f"    rendered: {line[:180]}\n"
                f"    normalised: {claim[:180]}"
            )
        pytest.fail(
            f"{len(unlisted)} rendered claim(s) credit an authority or assert a "
            f"rank without a citation. The allowlist has {len(allow)} entries.\n\n"
            "A citation must establish: WHICH document, WHICH year or round, and "
            "WHERE in it the figure appears. If the number is this tool's own "
            "judgement, mark it HOUSE — and the rendered text must say so on its "
            "face, not just the allowlist.\n\n"
            "If it is a rank, ask whether a distribution was actually loaded. "
            "Three separate labels in this package returned 'top_quartile' from "
            "a single >= against one number.\n\n"
            + "\n".join(detail)
        )


def test_allowlist_has_no_dead_entries(attributed_clauses):
    """An entry that no longer renders is stale; the list must describe reality."""
    dead = sorted(set(_load_allowlist()) - set(attributed_clauses))
    assert not dead, (
        f"{len(dead)} attribution allowlist entr(ies) no longer render. Remove "
        "them so the list stays a description of the shipped output:\n"
        + "\n".join(f"  {d}" for d in dead)
    )


def test_the_wrap_narrowing_cannot_absorb_a_new_claim():
    """N6 must swallow wraps and nothing else.

    Same three cases as the invariance gate's, against the real allowlist: a
    genuine fragment is absorbed, an invented attribution is not, and a
    fragment below the length floor is not.
    """
    ruled = set(_load_allowlist())
    parent = max(ruled, key=len)

    genuine = parent[: len(parent) - 10]
    assert wrapped_fragments({genuine}, ruled) == {genuine: parent}

    invented = "the cdfi fund ranks this cde in the top decile of applicants"
    assert wrapped_fragments({invented}, ruled) == {}, (
        "N6 absorbed a clause that is not a fragment of any ruled clause — it "
        "would then hide an uncited attribution, which is this gate's subject"
    )

    assert wrapped_fragments({parent[:MIN_FRAGMENT_CHARS - 1]}, ruled) == {}


def test_the_wrap_proof_refuses_a_clause_that_renders_beside_its_parent():
    """N6's surface rule goes red on a fragment-shaped lie — shown, not argued.

    ADDED IN 1.3.1 (G5), alongside the assertion that replaced the printed
    count. A proof that has never been seen to refuse is a proof nobody has
    evidence about.
    """
    ruled = set(_load_allowlist())
    parent = max(ruled, key=len)
    lie = parent[: len(parent) - 10]

    # Same surface as its parent: nothing wrapped it there.
    with pytest.raises(AssertionError, match=r"not wraps"):
        _assert_every_absorption_is_a_wrap(
            {lie: parent}, {lie: {"pdf"}, parent: {"pdf", "word"}})

    # Disjoint surfaces: a real wrap, and it passes.
    _assert_every_absorption_is_a_wrap(
        {lie: parent}, {lie: {"pdf"}, parent: {"word"}})

    # An absorption of something the corpus never rendered is refused too.
    with pytest.raises(AssertionError, match="not indexed"):
        _assert_every_absorption_is_a_wrap({lie: parent}, {parent: {"word"}})
