"""File-level metadata for the Word and Excel artifacts, from the CDE and the package.

WHY THIS MODULE EXISTS (1.7.1 R7). Through 1.7.0 neither renderer set a
document property, so every ``.docx`` this package wrote carried python-docx's
template defaults — author ``python-docx``, comments "generated by
python-docx", created and modified ``2013-12-23T23:15Z`` — and every
``.xlsx`` carried openpyxl's: creator ``openpyxl``, no title. A CDE files
these with a federal agency, and a document management system sorts on that
2013 date. credit-memo 0.2.2 found and fixed the same defect five days before
1.7.0 shipped; the flagship never got it.

WHAT IS SET, AND FROM WHERE. Nothing here is invented:

    author / creator      the CDE's name — a required profile field
    title                 the CDE's name and the round phrase the running
                          headers already print (``nmtc_round_phrase``), so
                          a round-less application titles itself without a
                          round rather than with ``None``
    comments / description  the package and version, read from
                          ``nmtcapp.__version__`` at call time so the
                          baseline's version-independence proof (which
                          monkeypatches it) holds for these too
    created / modified    (Word) the generation time, both the same: the
                          file is written once and never edited by this
                          package. openpyxl already stamps its own.

Subject, keywords, category and manager stay empty. The profile carries
none of them, and an empty property is honest where a guessed one is not.

Example::

    stamp_docx(doc, application)        # before doc.save(path)
    stamp_xlsx(wb, application)         # before wb.save(path)
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from nmtcapp.core.application_round import nmtc_round_phrase

if TYPE_CHECKING:
    from nmtcapp.core.application import Application


def generator_stamp() -> str:
    """``"nmtc-application-builder vX.Y.Z"`` — the phrase every surface prints."""
    from nmtcapp import __version__
    return f"nmtc-application-builder v{__version__}"


def document_title(application: "Application") -> str:
    """``"<CDE name> — NMTC CY 2026 Allocation Application"``, round permitting."""
    return (
        f"{application.cde.name} — "
        f"{nmtc_round_phrase(application.application_round)} Allocation Application"
    )


def stamp_docx(doc, application: "Application") -> None:
    """Set the python-docx core properties from the CDE and the package."""
    props = doc.core_properties
    props.author = application.cde.name
    props.title = document_title(application)
    props.comments = f"Generated by {generator_stamp()}"
    now = datetime.now(timezone.utc).replace(microsecond=0)
    props.created = now
    props.modified = now


def stamp_xlsx(wb, application: "Application") -> None:
    """Set the openpyxl workbook properties from the CDE and the package."""
    props = wb.properties
    props.creator = application.cde.name
    props.title = document_title(application)
    props.description = f"Generated by {generator_stamp()}"
