"""Markdown renderer — always-available fallback output format."""
from __future__ import annotations

import logging
from datetime import date
from typing import TYPE_CHECKING

from nmtcapp.renderers._disclosure import (
    is_partial_unverified, unverified_banner, unverified_ids,
    unverified_qualifier,
)
from nmtcapp.sections import ALL_SECTIONS
from nmtcapp.tables.distress_table import build_distress_table
from nmtcapp.tables.geographic_table import build_geographic_table
from nmtcapp.tables.impact_table import build_impact_table
from nmtcapp.tables.pipeline_table import build_pipeline_table
from nmtcapp.tables.track_record_table import build_track_record_table

if TYPE_CHECKING:
    from nmtcapp.core.application import Application, ApplicationAnalysis

logger = logging.getLogger(__name__)


class MarkdownApplicationBuilder:
    """Renders a complete NMTC application draft as clean Markdown.

    Markdown output is useful for version control diffs, review, and as
    a fallback when Word/PDF libraries are unavailable.

    Example::

        builder = MarkdownApplicationBuilder(application, analysis)
        md = builder.build()
        builder.save("./drafts/application.md")
    """

    def __init__(self, application: "Application", analysis: "ApplicationAnalysis") -> None:
        self.application = application
        self.analysis = analysis

    def build(self) -> str:
        """Build and return the full application as a Markdown string.

        Example::

            md = builder.build()
            print(md[:500])
        """
        parts = [
            self._cover(),
            self._executive_summary(),
            self._toc(),
        ]
        for section_gen in ALL_SECTIONS:
            parts.append(section_gen.generate_markdown(self.application, self.analysis))
        parts.append(self._appendix_pipeline())
        parts.append(self._appendix_distress())
        parts.append(self._appendix_geographic())
        parts.append(self._appendix_impact())
        parts.append(self._appendix_track_record())
        parts.append(self._methodology_note())
        return "\n\n---\n\n".join(parts)

    def save(self, path: str) -> None:
        """Save the Markdown document to a file.

        Example::

            builder.save("./output/application.md")
        """
        content = self.build()
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("Markdown application saved to %s (%d chars)", path, len(content))

    # ------------------------------------------------------------------
    # Private section builders
    # ------------------------------------------------------------------

    def _cover(self) -> str:
        from nmtcapp import __version__
        app = self.application
        score = self.analysis.readiness_score
        pr = self.analysis.pipeline_result
        degraded = getattr(pr, "eligibility_data_status", "ok") != "ok"

        banner = ""
        if degraded:
            banner = (
                "> **ELIGIBILITY DATA UNAVAILABLE — "
                f"{getattr(pr, 'eligibility_data_error', None) or 'reason unknown'}.** "
                "Census tract eligibility and distress figures could not be "
                "verified and are excluded from this document. Do not submit "
                "until eligibility data has been restored and re-verified.\n\n"
            )
        elif is_partial_unverified(pr):
            banner = f"> **UNVERIFIED PROJECT LOCATIONS — {unverified_banner(pr)}**\n\n"

        partial_tag = " (PARTIAL)" if getattr(score, "partial", False) else ""
        return (
            f"# NEW MARKETS TAX CREDIT ALLOCATION APPLICATION\n\n"
            f"**{app.cde.name}**\n\n"
            + banner +
            f"Application Round: {app.application_round}  \n"
            f"Requested Allocation: **${app.requested_allocation:,.0f}**  \n"
            f"Prepared: {date.today().isoformat()}  \n"
            f"Readiness Grade: **{score.grade}** ({score.overall_score:.1f}/100{partial_tag})  \n\n"
            f"---\n\n"
            # Read the real version. This line hardcoded "v0.1" while the
            # methodology note in the same document printed __version__, so
            # every markdown filing carried two contradictory self-attributions
            # and the cover page named a version that never existed. The
            # version stamp is the only way to tell a regenerated draft from a
            # 1.1.5 one, which is exactly what the 1.2.0 notes ask CDEs to do.
            f"*This document was generated by nmtc-application-builder "
            f"v{__version__}. "
            f"Narrative placeholders marked \\[NARRATIVE PLACEHOLDER\\] require CDE review and customization.*"
        )

    def _executive_summary(self) -> str:
        app = self.application
        pr = self.analysis.pipeline_result
        score = self.analysis.readiness_score
        d = pr.distress_breakdown
        degraded = getattr(pr, "eligibility_data_status", "ok") != "ok"

        if degraded:
            banner = (
                "**ELIGIBILITY DATA UNAVAILABLE — "
                f"{getattr(pr, 'eligibility_data_error', None) or 'reason unknown'}.** "
                "Census tract eligibility and distress figures could not be "
                "verified and are excluded from this document. Do not submit "
                "until eligibility data has been restored and re-verified.\n\n"
            )
            summary = (
                f"{app.cde.name} respectfully requests ${app.requested_allocation/1e6:.1f}MM in "
                f"New Markets Tax Credit allocation for application round {app.application_round}. "
                f"Our {pr.total_projects}-project pipeline spans "
                f"{pr.geographic_diversity.get('states_count', 0)} states. Census tract "
                "eligibility and distress concentration are unverified — eligibility "
                "data was unavailable when this draft was generated.\n\n"
            )
        elif is_partial_unverified(pr):
            banner = f"**UNVERIFIED PROJECT LOCATIONS — {unverified_banner(pr)}**\n\n"
            summary = (
                f"{app.cde.name} respectfully requests ${app.requested_allocation/1e6:.1f}MM in "
                f"New Markets Tax Credit allocation for application round {app.application_round}. "
                f"Our {pr.total_projects}-project pipeline spans "
                f"{pr.geographic_diversity.get('states_count', 0)} states with "
                f"**{d.get('pct_deep_or_severe', 0):.0%} of QEI {unverified_qualifier(pr)} "
                "committed to deep/severely distressed tracts** — figures reflect "
                "location-verified projects only.\n\n"
            )
        else:
            banner = ""
            summary = (
                f"{app.cde.name} respectfully requests ${app.requested_allocation/1e6:.1f}MM in "
                f"New Markets Tax Credit allocation for application round {app.application_round}. "
                f"Our {pr.total_projects}-project pipeline spans "
                f"{pr.geographic_diversity.get('states_count', 0)} states with "
                f"**{d.get('pct_deep_or_severe', 0):.0%} of QEI committed to deep/severely "
                f"distressed tracts**.\n\n"
            )

        partial_tag = " (PARTIAL)" if getattr(score, "partial", False) else ""
        return (
            f"## Executive Summary\n\n"
            + banner + summary +
            f"**Application Readiness Score: {score.overall_score:.1f}/100 "
            f"(Grade {score.grade}){partial_tag}**\n\n"
            f"**Key Strengths:**\n" +
            "\n".join(f"- {s}" for s in score.top_strengths) +
            f"\n\n**Recommended Improvements Before Submission:**\n" +
            "\n".join(f"- {r}" for r in score.recommendations[:3])
        )

    def _toc(self) -> str:
        lines = ["## Table of Contents\n"]
        for s in ALL_SECTIONS:
            lines.append(f"- [Section {s.section_id}: {s.title}](#section-{s.section_id.lower()})")
        lines.append("- [Appendix A: Pipeline Detail](#appendix-a)")
        lines.append("- [Appendix B: Distress Documentation](#appendix-b)")
        lines.append("- [Appendix C: Geographic Targeting](#appendix-c)")
        lines.append("- [Appendix D: Impact Projections](#appendix-d)")
        lines.append("- [Appendix E: Track Record](#appendix-e)")
        return "\n".join(lines)

    def _appendix_pipeline(self) -> str:
        df = build_pipeline_table(self.application.pipeline, self.application.cde)
        return f"## Appendix A: Pipeline Detail\n\n{_df_to_md(df, max_rows=25)}"

    def _appendix_distress(self) -> str:
        df = build_distress_table(self.application.pipeline)
        return f"## Appendix B: Distress Documentation\n\n{_df_to_md(df)}"

    def _appendix_geographic(self) -> str:
        df = build_geographic_table(self.application.pipeline)
        return f"## Appendix C: Geographic Targeting\n\n{_df_to_md(df)}"

    def _appendix_impact(self) -> str:
        df = build_impact_table(self.application.pipeline)
        return f"## Appendix D: Impact Projections\n\n{_df_to_md(df, max_rows=25)}"

    def _appendix_track_record(self) -> str:
        df = build_track_record_table(self.application.cde)
        return f"## Appendix E: CDE Track Record\n\n{_df_to_md(df)}"

    def _methodology_note(self) -> str:
        from nmtcapp import __version__
        pr = self.analysis.pipeline_result
        degraded = getattr(pr, "eligibility_data_status", "ok") != "ok"

        # Never cite a data source that did not load. Degraded mode means the
        # CDFI Fund eligibility table was NOT used anywhere in this draft.
        if degraded:
            eligibility_line = (
                "- Eligibility data: UNAVAILABLE — "
                f"{getattr(pr, 'eligibility_data_error', None) or 'reason unknown'}; "
                "no CDFI Fund eligibility data was loaded or used in this draft"
            )
        elif is_partial_unverified(pr):
            ids = unverified_ids(pr)
            eligibility_line = (
                "- Eligibility data: CDFI Fund NMTC Eligibility Table, 2016–2020 "
                f"ACS 5-Year Estimates — {len(ids)} of {pr.total_projects} projects "
                f"unverified (no census tract assigned): {', '.join(ids)}"
            )
        else:
            eligibility_line = (
                "- Eligibility data: CDFI Fund NMTC Eligibility Table, "
                "2016–2020 ACS 5-Year Estimates"
            )

        return (
            f"## Methodology Note\n\n"
            f"Generated by **nmtc-application-builder v{__version__}** on {date.today().isoformat()}.\n\n"
            f"{eligibility_line}\n"
            f"- Deal economics: nmtc-calc library (standard leveraged NMTC transaction structure)\n"
            f"- Impact benchmarks: CDFI Fund Annual Reports FY2018–FY2023\n"
            f"- Readiness scoring: an unsourced house heuristic of this tool. The weights "
            f"are not calibrated against award data, and the CDFI Fund publishes no such "
            f"weighting. NMTC rounds are announced by a NOAA (Notice of Allocation "
            f"Availability); the CY 2026 NOAA is not yet published.\n"
            f"- Community need: NOT generated by this tool — documented by the "
            f"CDE and cited to sources the CDE controls\n\n"
            f"All narrative sections marked \\[NARRATIVE PLACEHOLDER\\] require review and "
            f"customization before submission."
        )


def _df_to_md(df, max_rows: int = 50) -> str:
    """Convert DataFrame to a compact Markdown table."""
    if df is None or df.empty:
        return "_No data available._\n"
    display = df.head(max_rows)
    lines = []
    # Header
    lines.append("| " + " | ".join(str(c) for c in display.columns) + " |")
    lines.append("| " + " | ".join("---" for _ in display.columns) + " |")
    for _, row in display.iterrows():
        cells = []
        for v in row:
            if isinstance(v, float):
                cells.append(f"{v:,.2f}" if v > 1000 else f"{v:.3f}")
            else:
                cells.append(str(v).replace("|", "\\|"))
        lines.append("| " + " | ".join(cells) + " |")
    if len(df) > max_rows:
        lines.append(f"\n_Showing {max_rows} of {len(df)} rows._")
    return "\n".join(lines) + "\n"
