"""Markdown renderer — always-available fallback output format."""
from __future__ import annotations

import logging
from datetime import date
from typing import TYPE_CHECKING

from nmtcapp.sections import ALL_SECTIONS
from nmtcapp.tables.distress_table import build_distress_table
from nmtcapp.tables.geographic_table import build_geographic_table
from nmtcapp.tables.impact_table import build_impact_table
from nmtcapp.tables.pipeline_table import build_pipeline_table
from nmtcapp.tables.track_record_table import build_track_record_table

if TYPE_CHECKING:
    from nmtcapp.core.application import Application, ApplicationAnalysis

logger = logging.getLogger(__name__)


class MarkdownApplicationBuilder:
    """Renders a complete NMTC application draft as clean Markdown.

    Markdown output is useful for version control diffs, review, and as
    a fallback when Word/PDF libraries are unavailable.

    Example::

        builder = MarkdownApplicationBuilder(application, analysis)
        md = builder.build()
        builder.save("./drafts/application.md")
    """

    def __init__(self, application: "Application", analysis: "ApplicationAnalysis") -> None:
        self.application = application
        self.analysis = analysis

    def build(self) -> str:
        """Build and return the full application as a Markdown string.

        Example::

            md = builder.build()
            print(md[:500])
        """
        parts = [
            self._cover(),
            self._executive_summary(),
            self._toc(),
        ]
        for section_gen in ALL_SECTIONS:
            parts.append(section_gen.generate_markdown(self.application, self.analysis))
        parts.append(self._appendix_pipeline())
        parts.append(self._appendix_distress())
        parts.append(self._appendix_geographic())
        parts.append(self._appendix_impact())
        parts.append(self._appendix_track_record())
        parts.append(self._methodology_note())
        return "\n\n---\n\n".join(parts)

    def save(self, path: str) -> None:
        """Save the Markdown document to a file.

        Example::

            builder.save("./output/application.md")
        """
        content = self.build()
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info("Markdown application saved to %s (%d chars)", path, len(content))

    # ------------------------------------------------------------------
    # Private section builders
    # ------------------------------------------------------------------

    def _cover(self) -> str:
        app = self.application
        score = self.analysis.readiness_score
        return (
            f"# NEW MARKETS TAX CREDIT ALLOCATION APPLICATION\n\n"
            f"**{app.cde.name}**\n\n"
            f"Application Round: {app.application_round}  \n"
            f"Requested Allocation: **${app.requested_allocation:,.0f}**  \n"
            f"Prepared: {date.today().isoformat()}  \n"
            f"Readiness Grade: **{score.grade}** ({score.overall_score:.1f}/100)  \n\n"
            f"---\n\n"
            f"*This document was generated by nmtc-application-builder v0.1. "
            f"Narrative placeholders marked \\[NARRATIVE PLACEHOLDER\\] require CDE review and customization.*"
        )

    def _executive_summary(self) -> str:
        app = self.application
        pr = self.analysis.pipeline_result
        score = self.analysis.readiness_score
        d = pr.distress_breakdown
        return (
            f"## Executive Summary\n\n"
            f"{app.cde.name} respectfully requests ${app.requested_allocation/1e6:.1f}MM in "
            f"New Markets Tax Credit allocation for application round {app.application_round}. "
            f"Our {pr.total_projects}-project pipeline spans "
            f"{pr.geographic_diversity.get('states_count', 0)} states with "
            f"**{d.get('pct_deep_or_severe', 0):.0%} of QEI committed to deep/severely distressed tracts** "
            f"— ranking in the {d.get('vs_historical_winners', 'competitive').replace('_', ' ')} "
            f"tier of historical NMTC applications.\n\n"
            f"**Application Readiness Score: {score.overall_score:.1f}/100 (Grade {score.grade})**\n\n"
            f"**Key Strengths:**\n" +
            "\n".join(f"- {s}" for s in score.top_strengths) +
            f"\n\n**Recommended Improvements Before Submission:**\n" +
            "\n".join(f"- {r}" for r in score.recommendations[:3])
        )

    def _toc(self) -> str:
        lines = ["## Table of Contents\n"]
        for s in ALL_SECTIONS:
            lines.append(f"- [Section {s.section_id}: {s.title}](#section-{s.section_id.lower()})")
        lines.append("- [Appendix A: Pipeline Detail](#appendix-a)")
        lines.append("- [Appendix B: Distress Documentation](#appendix-b)")
        lines.append("- [Appendix C: Geographic Targeting](#appendix-c)")
        lines.append("- [Appendix D: Impact Projections](#appendix-d)")
        lines.append("- [Appendix E: Track Record](#appendix-e)")
        return "\n".join(lines)

    def _appendix_pipeline(self) -> str:
        df = build_pipeline_table(self.application.pipeline, self.application.cde)
        return f"## Appendix A: Pipeline Detail\n\n{_df_to_md(df, max_rows=25)}"

    def _appendix_distress(self) -> str:
        df = build_distress_table(self.application.pipeline)
        return f"## Appendix B: Distress Documentation\n\n{_df_to_md(df)}"

    def _appendix_geographic(self) -> str:
        df = build_geographic_table(self.application.pipeline)
        return f"## Appendix C: Geographic Targeting\n\n{_df_to_md(df)}"

    def _appendix_impact(self) -> str:
        df = build_impact_table(self.application.pipeline)
        return f"## Appendix D: Impact Projections\n\n{_df_to_md(df, max_rows=25)}"

    def _appendix_track_record(self) -> str:
        df = build_track_record_table(self.application.cde)
        return f"## Appendix E: CDE Track Record\n\n{_df_to_md(df)}"

    def _methodology_note(self) -> str:
        from nmtcapp import __version__
        return (
            f"## Methodology Note\n\n"
            f"Generated by **nmtc-application-builder v{__version__}** on {date.today().isoformat()}.\n\n"
            f"- Eligibility data: CDFI Fund NMTC Eligibility Table, 2016–2020 ACS 5-Year Estimates\n"
            f"- Deal economics: nmtc-calc library (standard leveraged NMTC transaction structure)\n"
            f"- Impact benchmarks: CDFI Fund Annual Reports FY2018–FY2023\n"
            f"- Readiness scoring: proprietary scoring model based on CDFI Fund NOFA criteria\n"
            f"- HMDA community need: FFIEC HMDA LAR, 5-year aggregated data\n\n"
            f"All narrative sections marked \\[NARRATIVE PLACEHOLDER\\] require review and "
            f"customization before submission."
        )


def _df_to_md(df, max_rows: int = 50) -> str:
    """Convert DataFrame to a compact Markdown table."""
    if df is None or df.empty:
        return "_No data available._\n"
    display = df.head(max_rows)
    lines = []
    # Header
    lines.append("| " + " | ".join(str(c) for c in display.columns) + " |")
    lines.append("| " + " | ".join("---" for _ in display.columns) + " |")
    for _, row in display.iterrows():
        cells = []
        for v in row:
            if isinstance(v, float):
                cells.append(f"{v:,.2f}" if v > 1000 else f"{v:.3f}")
            else:
                cells.append(str(v).replace("|", "\\|"))
        lines.append("| " + " | ".join(cells) + " |")
    if len(df) > max_rows:
        lines.append(f"\n_Showing {max_rows} of {len(df)} rows._")
    return "\n".join(lines) + "\n"
